name: Welcome first time contributors

on:
  pull_request_target:
    types:
      - opened
  issues:
    types:
      - opened

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            Welcome to CaptainCSS! Thanks a lot for reporting your first issue.

            If you haven't already, please read our [Contributing Guidelines](https://github.com/hex-digital/captaincss/blob/main/.github/CONTRIBUTING.md).
          pr-message: |
            Welcome to CaptainCSS. Thanks a lot for creating your first pull request.

            If you haven't already, please read our [Contributing Guidelines](https://github.com/hex-digital/captaincss/blob/main/.github/CONTRIBUTING.md).
